### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by MrKilgore94** [brendacassita/FreshPotatoes#100]
No reviews listed

## Steps To Reproduce

1. Click on movie title
2. Scroll
3. look for listed reviews
4. No reviews being listed
5. Write review
6. Written review not being listed

## The current behavior

No reviews listed until user created one.
Review in stringify form
Once paged is refreshed no review is listed(even the one the user creates)

## The expected behavior

Expected to see pre populated reviews and reviews user makes

**Comment by jess215** [comment]
Currently working on adding this, thanks!
