### ISSUE TITLE
Star Review

### ISSUE THREAD

**Issue by Randycl808** [brendacassita/FreshPotatoes#101]
When navigating to any movie, when going to the bottom to leave a review, the stars rating automatically loads '2.0 stars' 'meh, it passed the time.' Which gives the client a negative impression of all movies before they get it rate it themselves.

## Steps To Reproduce

1. Click on any movie, navigate to the 'Movie show" page
2. Scroll to the bottom by the reviews
3. The rating is pre-populated at 2.0 stars

## The current behavior

'2.0 stars' 'meh, 'it passed the time'

## The expected behavior

'0.0 stars' 'Submit a rating' 

<img width="1440" alt="Screen Shot 2022-04-22 at 2 25 05 PM" src="https://user-images.githubusercontent.com/99686175/164797118-ddbec918-50ef-4399-9067-d65edd948dce.png">

**Comment by jess215** [comment]
Thank you, that's helpful feedback!
