### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by TheSteveIsGreat** [brendacassita/FreshPotatoes#102]
I'm unsure if my comment has been sent or posted anywhere after clicking submit.

## Steps To Reproduce

1. go to 'contact' link in footer
2. fill out form
3. click submit

## The current behavior
Nothing happens when I click submit

## The expected behavior
I should be told whether or not my comment was submitted successfully

**Comment by jess215** [comment]
Duplicate bug report, thanks!
