### ISSUE TITLE
Popular Fries pages

### ISSUE THREAD

**Issue by MrKilgore94** [brendacassita/FreshPotatoes#103]
Popular Fries pages not loading next page

## Steps To Reproduce

1. Go to "Popular Fires"
2. Scroll down
3.  Click "Page 2"
4. "Page 2" dosent load

## The current behavior

Sits on page 1

## The expected behavior

Loads page 2

**Comment by jess215** [comment]
Thank you, we'll have to look at where this broke. This is really helpful.

**Comment by brendacassita** [comment]
closed
