### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by JoeJorgensen** [brendacassita/FreshPotatoes#104]
## Steps To Reproduce

1. Go to edit profile.
2. Just type the name and nothing else. 
3. Press save changes

## The current behavior
I get an error and the name doesn't update

## The expected behavior
As a user I would like just my name to update 

![Screen Shot 2022-04-22 at 3 23 44 PM](https://user-images.githubusercontent.com/99521938/164798399-f37454e7-77b3-4a3c-bcd8-9aca49cc42c8.png)

**Comment by brendacassita** [comment]
page now auto refreshes after updating name
