### ISSUE TITLE
Account footer

### ISSUE THREAD

**Issue by MrKilgore94** [brendacassita/FreshPotatoes#105]
No info in "Account" on the footer

## Steps To Reproduce

1. Scroll to footer
2. No "Account" info
3.  Login
4.  Still no "Account" info

## The current behavior

No Account info
![Screen Shot 2022-04-22 at 15 32 15](https://user-images.githubusercontent.com/99686234/164798737-1d9f7bc2-b25a-4b9d-9ae8-4816dbf0e6c0.png)

## The expected behavior

Listed users account info

**Comment by jess215** [comment]
Working as intended for now, thanks!
