### ISSUE TITLE
Updating just email removes my name

### ISSUE THREAD

**Issue by JoeJorgensen** [brendacassita/FreshPotatoes#108]
## Steps To Reproduce

1. Go to edit profile.
2. Just type the email and nothing else. 
3. Press save changes

## The current behavior
Removes the name, and updates email.

## The expected behavior
I would like for just my email to update
![Screen Shot 2022-04-22 at 3 32 08 PM](https://user-images.githubusercontent.com/99521938/164799033-3cd3c929-56fd-4e8d-89f4-22c106e6ba55.png)

**Comment by jess215** [comment]
Were the fields pre-populated with anything or were they blank? We haven't been able to replicate this so we'll need to keep investigating.

**Comment by JoeJorgensen** [comment]
The fields were pre populated I deleted the name. It might help to make the name value required.
