### ISSUE TITLE
Privay Policy

### ISSUE THREAD

**Issue by MrKilgore94** [brendacassita/FreshPotatoes#109]
Red Links not actually clickable (I.E. "Click here to learn more")

## Steps To Reproduce

1. Go to "Privay Policy" page
2. Scroll
3.  Click "Click here to learn more" 
4.  Nothing heppens

## The current behavior

Red Links not actually clickable (I.E. "Click here to learn more")

## The expected behavior

Take you to a different page or a different section of the same page

**Comment by MrKilgore94** [comment]
https://user-images.githubusercontent.com/99686234/164799752-0ceee7e5-8783-41ce-a1e5-aa228c66cb07.mov

**Comment by jess215** [comment]
Yep, we haven't updated that yet. Thanks!

**Comment by brendacassita** [comment]
contact us links now working, privacy page updated
