### ISSUE TITLE
Can't see Popularpotatoes/fries page when logged out

### ISSUE THREAD

**Issue by Randycl808** [brendacassita/FreshPotatoes#110]
When logged out, as an unregistered client I don't have access to any 'movies show' pages and their reviews, which would be helpful to see if I haven't created an account yet.

## Steps To Reproduce

1. Log out/ Don't be signed in
2. Click on any movie/ popular potatoes or fries page
3. It will require a login to see the show page

## The current behavior

Navigates you to a login in page, which is required to see the movies rating/ details.

## The expected behavior

Allows you to see the ratings/ movie in detail. But cannot rate stars w/o having a account.

**Comment by jess215** [comment]
That's an intended feature. Thanks!
