### ISSUE TITLE
After registering I can't add a photo

### ISSUE THREAD

**Issue by JoeJorgensen** [brendacassita/FreshPotatoes#111]
## Steps To Reproduce

1. Go to edit profile.
2. Try to click on 'no image '
3. Nothing happens

## The current behavior
There is no way to add an image after creating a user.

## The expected behavior
I would like to add an image to my profile, and all I see is text that says no image. 

![Screen Shot 2022-04-22 at 3 41 28 PM](https://user-images.githubusercontent.com/99521938/164800037-4c7f2b92-5fd5-484b-8440-ef72cd9030ca.png)

**Comment by jess215** [comment]
Fixed, thanks!
