### ISSUE TITLE
Edit profile bug

### ISSUE THREAD

**Issue by Randycl808** [brendacassita/FreshPotatoes#94]
When updating the name field in 'edit profile' after clicking 'save changes' it doesnt refresh the page and update the name until the client refreshes it themselves.

## Steps To Reproduce

1. Click on 'edit profile'
2. Change the name
3. Click 'save change'
4. No update until client refreshes 

## The current behavior

After saving changes. Client needs to update using the refresh button.

## The expected behavior

App automatically updates after clicking 'save change'

**Comment by jess215** [comment]
Thank you, we'll work on implementing that!

**Comment by brendacassita** [comment]
page now auto refreshes after updating name
