### ISSUE TITLE
Review bug

### ISSUE THREAD

**Issue by Randycl808** [brendacassita/FreshPotatoes#97]
When submitting a review in the movie-showpage, the review doesn't save to the UI, after refreshing the page the JSON disappears. Causing the client to lose the JSON, and re-submit another entry.

## Steps To Reproduce

1. Click any movie to leave a review
2. Add the stars then click 'submit review'
3. Refresh page and the JSON disappears. 

## The current behavior
Movie review doesn't save JSON after refreshing.

## The expected behavior
After refreshing, the JSON will be saved, even when going to other pages.

**Comment by jess215** [comment]
The JSON is only showing the input into the form, so it wouldn't be saving. We're still currently working on getting the reviews up on each movie. Thanks!
