### ISSUE TITLE
Landing/Home page, Carousel button.

### ISSUE THREAD

**Issue by Randycl808** [brendacassita/FreshPotatoes#99]
When using the scroll button to browse different movies, if you continue to scroll it will overlap movies, then eventually allow you to keep scrolling past all the movies loading a blank screen.

## Steps To Reproduce

1. Navigate to the home/landing page
2. Use the scroll button to the RIGHT, after doing it 5-10 times, it'll scroll past all the movies.

## The current behavior

Scrolling to the right never stops causing it to scroll past all the movies. 

## The expected behavior

When scrolling to the right, it 1) stops and makes you scroll back or 2)starts to load movies from the beginning.

<img width="1440" alt="Screen Shot 2022-04-22 at 2 20 27 PM" src="https://user-images.githubusercontent.com/99686175/164797342-f20fcab6-26da-4b62-973f-bd5da85f1d39.png">

**Comment by jess215** [comment]
Known issue, thanks!
